name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update apt
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt update
    - name: check g++
      run: apt-cache search gcc
    - name: get gtest
      run: sudo apt-get install googletest 
    - name: install gtest 
      working-directory: /usr/src/googletest
      run: sudo cmake . && sudo cmake --build . --target install
    - name: create build directory
      run: mkdir -p build
    - name: build
      working-directory: ./build
      run: cmake .. && make
